#pragma once
#include <vector>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <deque>
#include <map>
#include <set>
#include <cmath>
#include <random>
#include <algorithm>
#include <array>
#include <optional>
#include <cstdint>
#include <thread>
#include <mutex>
