#pragma once

#include <iostream>
#include <memory>
#include <string>
#include <string_view>
#include <cassert>
#include <stdexcept>
#include <cstdint>
#include <limits>
#include <cmath>
#include <utility>
#include <type_traits>
#include <initializer_list>
#include <thread>
#include <future>
#include <mutex>
#include <shared_mutex>
#include <algorithm>
#include <array>
#include <vector>
#include <map>
#include <set>
#include <unordered_set>
#include <unordered_map>
#include <list>