#pragma once
#include "Core.h"

#include "Game/AssetLoaderFactory.h"
#include "Game/Collision.h"
#include "Game/GameManager.h"
#include "Game/GameObject.h"
#include "Game/Input.h"
#include "Game/Prefab.h"
#include "Game/SMath.h"
#include "Game/ScriptableObject.h"
#include "Game/Vector.h"
#include "Game/World.h"

#include "Game/Asset/BinaryAsset.h"
#include "Game/Asset/FontAsset.h"
#include "Game/Asset/MaterialAsset.h"
#include "Game/Asset/MeshAsset.h"
#include "Game/Asset/ModelAsset.h"
#include "Game/Asset/PrefabAsset.h"
#include "Game/Asset/ScriptableObjectAsset.h"
#include "Game/Asset/ShaderAsset.h"
#include "Game/Asset/SoundAsset.h"
#include "Game/Asset/TextAsset.h"
#include "Game/Asset/TextureAsset.h"
#include "Game/Asset/WorldAsset.h"

#include "Game/Component/Component.h"
#include "Game/Component/Transform.h"
#include "Game/Component/FollowTarget.h"

#include "Game/Component/Network/NetworkComponent.h"
#include "Game/Component/Network/UdpClient.h"
#include "Game/Component/Network/UdpServer.h"

#include "Game/Component/Phys/BoxCollider.h"
#include "Game/Component/Phys/CapsuleCollider.h"
#include "Game/Component/Phys/Collider.h"
#include "Game/Component/Phys/ConvexCollider.h"
#include "Game/Component/Phys/RigidBody.h"
#include "Game/Component/Phys/SphereCollider.h"

#include "Game/Component/Render/Camera.h"
#include "Game/Component/Render/DebugRenderer.h"
#include "Game/Component/Render/DirectionalLight.h"
#include "Game/Component/Render/LineRenderer.h"
#include "Game/Component/Render/MeshRenderer.h"
#include "Game/Component/Render/PointLight.h"
#include "Game/Component/Render/TextRenderer.h"
#include "Game/Component/Sound/AudioSource.h"

#include "Physics/ContactPoint.h"
#include "Physics/HitPoint.h"
#include "Physics/PhysicsEvent.h"
#include "Physics/PhysWorld.h"
#include "Physics/Ray.h"

#include "Render/AABB.h"
#include "Render/Font.h"
#include "Render/Material.h"
#include "Render/MaterialPropertyBlock.h"
#include "Render/Mesh.h"
#include "Render/Model.h"
#include "Render/RenderTagList.h"
#include "Render/Shader.h"
#include "Render/Texture.h"

#include "Sound/SoundClip.h"
